### ISSUE TITLE
Weapon Master Relic

### ISSUE THREAD

**Issue by QGoh** [OmbudRov/Spec-Overlay#1]
Would it be possible to also make this plugin work with the spec relic in trailblazer league?

**Comment by OmbudRov** [comment]
i dont have the axe on leagues but it should be working fine. If its not working, would it possible for you to attach a video showing so?

**Comment by QGoh** [comment]
The trailblazer spec relic has the same UI that replaces the spec bar and hides the spec percentage: https://i.imgur.com/qSoXsQ7.png

I was looking for something that would always show me my actual spec percentage and found this plugin but it only works when an axe is equipped.

**Comment by OmbudRov** [comment]
alright, i'll add functionality to overlay the spec for the relic _soon™_

**Comment by OmbudRov** [comment]
after much thought, i dont think i'll be adding this. Sorry
